/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as Blog2Import } from './routes/blog2'
import { Route as Blog1Import } from './routes/blog1'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const Blog2Route = Blog2Import.update({
  id: '/blog2',
  path: '/blog2',
  getParentRoute: () => rootRoute,
} as any)

const Blog1Route = Blog1Import.update({
  id: '/blog1',
  path: '/blog1',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/blog1': {
      id: '/blog1'
      path: '/blog1'
      fullPath: '/blog1'
      preLoaderRoute: typeof Blog1Import
      parentRoute: typeof rootRoute
    }
    '/blog2': {
      id: '/blog2'
      path: '/blog2'
      fullPath: '/blog2'
      preLoaderRoute: typeof Blog2Import
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog1': typeof Blog1Route
  '/blog2': typeof Blog2Route
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog1': typeof Blog1Route
  '/blog2': typeof Blog2Route
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog1': typeof Blog1Route
  '/blog2': typeof Blog2Route
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/blog1' | '/blog2'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/blog1' | '/blog2'
  id: '__root__' | '/' | '/about' | '/blog1' | '/blog2'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  Blog1Route: typeof Blog1Route
  Blog2Route: typeof Blog2Route
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  Blog1Route: Blog1Route,
  Blog2Route: Blog2Route,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/blog1",
        "/blog2"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/blog1": {
      "filePath": "blog1.tsx"
    },
    "/blog2": {
      "filePath": "blog2.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
